# Generated by Django 5.1.2 on 2025-07-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IER_ENTRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('Terminé', 'Terminé'), ('En Attente', 'En Attente')], default='En Attente', max_length=10)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ier_entre', to='conteneurs.dossier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IER_SORTIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('Terminé', 'Terminé'), ('En Attente', 'En Attente')], default='En Attente', max_length=10)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ier_sortie', to='conteneurs.dossier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
