# Generated by Django 5.1.2 on 2025-08-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0002_ier_entre_ier_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Personnel_pays',
            field=models.CharField(choices=[('côte_ivoire', 'côte_ivoire'), ('Ghana', 'Ghana'), ('Nigeria', 'Nigeria'), ('Bénin', 'Bénin'), ('Gabon', 'Gabon'), ('liberia', 'liberia'), ('Mauritanie', 'Mauritanie')], default='côte_ivoire', max_length=20),
        ),
    ]
