# Generated by Django 5.1.2 on 2026-01-20 09:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0003_alter_personnel_personnel_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='poids_brute',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conteneur',
            name='poids_equipements',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='conteneur',
            name='poids_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
