# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneurbase',
            name='Plombs_oils',
            field=models.CharField(blank=True, help_text='Numéros de plombs huiles (séparés par virgule)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='Temerature',
            field=models.FloatField(blank=True, null=True, verbose_name='Température (°C)'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='statut',
            field=models.CharField(choices=[('non_empote', 'Non empoté'), ('empote', 'Empoté')], default='non_empote', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='TRD',
            field=models.CharField(max_length=50, verbose_name='Numéro TRD'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('selection_en_cours', 'Sélection en cours'), ('empotage_en_cours', 'Empotage en cours'), ('dossier_termine', 'Terminé'), ('annulé', 'Annulé')], default='en_attente', max_length=25),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='plombs_amateur',
            field=models.CharField(blank=True, help_text='Numéros de plombs amateur (séparés par virgule)', max_length=200, null=True),
        ),
    ]
