# Generated by Django 6.0.7 on 2026-07-14 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0002_alter_conteneurbase_plombs_oils_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isotanks',
            old_name='photoplomb1',
            new_name='photoPlombAmateur1',
        ),
        migrations.RenameField(
            model_name='isotanks',
            old_name='photoplomb2',
            new_name='photoPlombAmateur2',
        ),
        migrations.RenameField(
            model_name='isotanks',
            old_name='photoplomb3',
            new_name='photoPlombAmateur3',
        ),
        migrations.RenameField(
            model_name='isotanks',
            old_name='plomb1',
            new_name='plombAmateur1',
        ),
        migrations.RenameField(
            model_name='isotanks',
            old_name='plomb2',
            new_name='plombAmateur2',
        ),
        migrations.RenameField(
            model_name='isotanks',
            old_name='plomb3',
            new_name='plombAmateur3',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='Plombs_oils',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='pd',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_plombs_oils',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='poids_brute',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='poids_equipements',
        ),
        migrations.AddField(
            model_name='flexitanks',
            name='Plombs_oils',
            field=models.CharField(blank=True, help_text='Numéros de plombs  (séparés par virgule)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flexitanks',
            name='photo_plombs_oils',
            field=models.ImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils/'),
        ),
        migrations.AddField(
            model_name='flexitanks',
            name='poids_brute',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flexitanks',
            name='poids_equipements',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='isotanks',
            name='Plombs_oils1',
            field=models.CharField(blank=True, help_text='Numéros de plombs  (séparés par virgule)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='isotanks',
            name='Plombs_oils2',
            field=models.CharField(blank=True, help_text='Numéros de plombs  (séparés par virgule)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='isotanks',
            name='photo_plombs_oils1',
            field=models.ImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils1/'),
        ),
        migrations.AddField(
            model_name='isotanks',
            name='photo_plombs_oils2',
            field=models.ImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils2/'),
        ),
    ]
