# Generated by Django 6.0.7 on 2026-07-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0003_rename_photoplomb1_isotanks_photoplombamateur1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isotanks',
            old_name='conteneur',
            new_name='iso',
        ),
    ]
