# Generated by Django 6.0.7 on 2026-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0004_rename_conteneur_isotanks_iso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteneurbase',
            options={'ordering': ['reference'], 'verbose_name': 'Conteneur base', 'verbose_name_plural': 'Conteneurs base'},
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='Plombs_oils',
            field=models.CharField(blank=True, help_text='Numéros de plombs ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='plombs_amateur',
            field=models.CharField(blank=True, help_text='Numéros de plombs amateur  ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='Plombs_oils1',
            field=models.CharField(blank=True, help_text='Numéros de plombs ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='Plombs_oils2',
            field=models.CharField(blank=True, help_text='Numéros de plombs  ', max_length=200, null=True),
        ),
    ]
