# Generated by Django 6.0.7 on 2026-07-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0005_alter_conteneurbase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='Id_Personel',
            new_name='Id_Personnel',
        ),
    ]
