# Generated by Django 6.0.7 on 2026-07-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0006_rename_id_personel_dossier_id_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='date_de_fin_d_empotage',
        ),
    ]
