# Generated by Django 6.0.7 on 2026-07-16 15:48
# Réordonnée à la main : le modèle SelectionDossier est créé, les données
# existantes sont migrées depuis ConteneurBase, puis les anciens champs
# photo sont retirés de ConteneurBase.

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


CHAMPS_PHOTOS_SOURCE = [
    'photo_devant',
    'photo_derriere',
    'photo_interieur',
    'photo_lateral_droit',
    'photo_lateral_gauche',
]


def migrer_photos_vers_selection_dossier(apps, schema_editor):
    """Pour chaque dossier, reprend les 5 photos du premier conteneur qui les
    a toutes, et les copie dans sa fiche de sélection unique.

    Limite structurelle assumée : SelectionDossier est OneToOne sur Dossier,
    alors que ces photos étaient auparavant répétées sur chaque conteneur.
    Un seul jeu de photos par dossier peut donc être conservé ; les photos
    des autres conteneurs du même dossier restent en base (colonnes encore
    présentes à cette étape de la migration) mais ne sont plus reliées à
    aucune fiche après la suppression des champs qui suit.
    """
    ConteneurBase = apps.get_model('conteneurs', 'ConteneurBase')
    Dossier = apps.get_model('conteneurs', 'Dossier')
    SelectionDossier = apps.get_model('conteneurs', 'SelectionDossier')

    for dossier in Dossier.objects.all():
        conteneurs = ConteneurBase.objects.filter(dossier=dossier).order_by('date_created')
        source = next(
            (c for c in conteneurs if all(getattr(c, champ) for champ in CHAMPS_PHOTOS_SOURCE)),
            None,
        )
        if source is None:
            continue

        SelectionDossier.objects.create(
            dossier=dossier,
            date_selection=dossier.date_de_selection or source.date_created,
            agent_selection_id=dossier.Id_Agent_selection_id,
            photo_avant=source.photo_devant,
            photo_arriere=source.photo_derriere,
            photo_interieure=source.photo_interieur,
            photo_laterale_droite=source.photo_lateral_droit,
            photo_laterale_gauche=source.photo_lateral_gauche,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0007_remove_dossier_date_de_fin_d_empotage'),
        ('users', '0005_users_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionDossier',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_selection', models.DateTimeField(verbose_name='Date de sélection')),
                ('photo_avant', models.ImageField(upload_to='selections/avant/', verbose_name='Photo avant')),
                ('photo_arriere', models.ImageField(upload_to='selections/arriere/', verbose_name='Photo arrière')),
                ('photo_interieure', models.ImageField(upload_to='selections/interieure/', verbose_name='Photo intérieure')),
                ('photo_laterale_droite', models.ImageField(upload_to='selections/laterale_droite/', verbose_name='Photo latérale droite')),
                ('photo_laterale_gauche', models.ImageField(upload_to='selections/laterale_gauche/', verbose_name='Photo latérale gauche')),
                ('agent_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_selection', to='users.agent_selection')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='conteneurs.dossier')),
            ],
            options={
                'verbose_name': 'Fiche de sélection',
                'verbose_name_plural': 'Fiches de sélection',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.RunPython(migrer_photos_vers_selection_dossier, noop_reverse),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_derriere',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_devant',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_interieur',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_lateral_droit',
        ),
        migrations.RemoveField(
            model_name='conteneurbase',
            name='photo_lateral_gauche',
        ),
    ]
