# Generated by Django 6.0.7 on 2026-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0009_revert_selection_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneurbase',
            name='photo_debut',
            field=models.ImageField(blank=True, null=True, upload_to='conteneurs/debut/'),
        ),
    ]
