# Generated by Django 6.0.7 on 2026-07-16 16:27

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0010_conteneurbase_photo_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_debut',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/debut/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_derriere',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/derriere/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_devant',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/devant/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_fin',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/fin/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_interieur',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/interieur/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_lateral_droit',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/lateral_droit/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_lateral_gauche',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/lateral_gauche/'),
        ),
        migrations.AlterField(
            model_name='conteneurbase',
            name='photo_pendant',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/pendant/'),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='Photoheatingpad',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='flexitanks/heatingpad/'),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='photoFlextank',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='flexitanks/photos/'),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='photo_plombs_oils',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils/'),
        ),
        migrations.AlterField(
            model_name='flexitanks',
            name='plombs_amateur_photo',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='flexitanks/plombs_amateur/'),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='photoPlombAmateur1',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='isotanks/plombs/'),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='photoPlombAmateur2',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='isotanks/plombs/'),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='photoPlombAmateur3',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='isotanks/plombs/'),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='photo_plombs_oils1',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils1/'),
        ),
        migrations.AlterField(
            model_name='isotanks',
            name='photo_plombs_oils2',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='conteneurs/plombs_oils2/'),
        ),
    ]
