# Generated by Django 6.0.7 on 2026-07-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0013_conteneur_mixin_refactor_pivot_drop'),
        ('users', '0006_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='Id_Agent_operationel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_operationnel', to='users.personnel'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='Id_Personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to='users.personnel'),
        ),
    ]
