# Generated by Django 5.2.16 on 2026-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0014_dossier_id_agent_operationel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='commentaire_soumission',
            field=models.TextField(blank=True, verbose_name='Commentaire de soumission'),
        ),
    ]
