# Generated by Django 5.2.16 on 2026-07-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0015_dossier_commentaire_soumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='commentaire_creation',
            field=models.TextField(blank=True, verbose_name='Commentaire de création'),
        ),
    ]
