# Generated by Django 5.2.16 on 2026-07-22 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0016_dossier_commentaire_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-date_created'], 'permissions': [('can_valider_paiement', "Peut valider le paiement d'un dossier")], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
        migrations.AddField(
            model_name='dossier',
            name='commentaire_paiement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='utilisateur_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
