# Generated by Django 5.2.16 on 2026-07-23 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0018_groupe_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='montant_paiement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='preuve_paiement',
            field=models.FileField(blank=True, null=True, upload_to='paiements/preuves/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
