# Generated by Django 5.2.16 on 2026-07-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0019_dossier_montant_paiement_dossier_preuve_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-date_created'], 'permissions': [('can_valider_paiement', "Peut valider le paiement d'un dossier"), ('can_voir_paiements', 'Peut voir le suivi des paiements des dossiers')], 'verbose_name': 'Dossier', 'verbose_name_plural': 'Dossiers'},
        ),
    ]
