# Generated by Django 5.2.16 on 2026-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0020_alter_dossier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_modifier',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flexitanks',
            name='date_modifier',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='isotanks',
            name='date_modifier',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
