# Generated by Django 5.2.16 on 2026-09-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0021_dossier_date_modifier_flexitanks_date_modifier_and_more'),
        ('users', '0010_cliententreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='Id_ClientEntreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='users.cliententreprise'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sortie_stock_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sortie_stock_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
