# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date_created'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'ordering': ['type_document'], 'verbose_name': 'Type de document', 'verbose_name_plural': 'Types de documents'},
        ),
    ]
