# Generated by Django 6.0.7 on 2026-07-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Anciennes valeurs de statut (Terminé/EnAttente) -> nouveau jeu d'états, plus
# fin, permettant de distinguer un document déposé de sa validation.
ANCIEN_VERS_NOUVEAU = {
    'Terminé':   'valide',
    'EnAttente': 'en_attente_validation',
}


def migrer_statuts_existants(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for ancien, nouveau in ANCIEN_VERS_NOUVEAU.items():
        Document.objects.filter(statut=ancien).update(statut=nouveau)


def revenir_aux_anciens_statuts(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for ancien, nouveau in ANCIEN_VERS_NOUVEAU.items():
        Document.objects.filter(statut=nouveau).update(statut=ancien)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_typedocument_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('ajoute', 'Ajouté'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='ajoute', max_length=25),
        ),
        migrations.RunPython(migrer_statuts_existants, revenir_aux_anciens_statuts),
    ]
