# Generated by Django 6.0.7 on 2026-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteneurs', '0006_rename_id_personel_dossier_id_personnel'),
        ('users', '0002_alter_agent_empotage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personel',
            new_name='Personnel',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('agent_selection', 'Agent de Sélection'), ('agent_acconage', 'Agent Habillage & Empotage'), ('personnel', 'Personnel'), ('client', 'Client')], max_length=20),
        ),
    ]
