# Generated by Django 6.0.7 on 2026-07-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_personel_personnel_alter_users_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('agent_selection', 'Agent de Sélection'), ('agent_empotage', 'Agent Habillage & Empotage'), ('personnel', 'Personnel'), ('client', 'Client')], max_length=20),
        ),
    ]
