# Generated by Django 6.0.7 on 2026-07-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0002_alter_commodite_options_and_more'),
        ('users', '0004_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='referentiels.pays'),
        ),
    ]
