# Generated by Django 6.0.7 on 2026-07-16 16:27

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='users/photos/'),
        ),
    ]
