# Generated by Django 5.2.16 on 2026-07-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('agent_selection', 'Agent de Sélection'), ('agent_empotage', 'Agent Habillage & Empotage'), ('personnel', 'Personnel'), ('client', 'Client'), ('comptable', 'Comptable')], max_length=20),
        ),
    ]
