# Generated by Django 5.2.16 on 2026-07-22 17:26

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelComptable',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_comptable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel comptable',
                'verbose_name_plural': 'Personnel comptable',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
