# Generated by Django 5.2.16 on 2026-09-23 16:29

import django.utils.timezone
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_users_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEntreprise',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('stock_client_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Société cliente',
                'verbose_name_plural': 'Sociétés clientes',
                'ordering': ['nom'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
