# Generated by Django 5.2.16 on 2026-09-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_cliententreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='users.cliententreprise'),
        ),
    ]
