# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
