# Generated by Django 6.0.7 on 2026-07-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('info', 'Information'), ('alerte', 'Alerte')], default='info', max_length=10),
        ),
    ]
