# Generated by Django 5.2.16 on 2026-08-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('notification', '0004_notification_dossier_notification_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('dossier_cree', 'Dossier créé'), ('paiement_valide', 'Paiement validé'), ('changement_statut', 'Changement de statut'), ('document_ajoute', 'Document ajouté'), ('retour_selection', 'Retour en sélection'), ('retour_empotage', 'Retour en empotage'), ('nouveau_message', 'Nouveau message'), ('ajout_groupe', 'Ajout à un groupe'), ('ajout_conversation', 'Ajout à une conversation'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
