# Generated by Django 5.2.16 on 2026-07-27 16:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_action_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('result_snapshot', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action synchronisee',
                'verbose_name_plural': 'Actions synchronisees',
                'ordering': ['-applied_at'],
            },
        ),
    ]
