# Generated by Django 6.0.7 on 2026-07-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('download', 'Téléchargement'), ('submit', 'Soumission')], max_length=10),
        ),
    ]
