# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodite',
            options={'ordering': ['nom'], 'verbose_name': 'Commodité', 'verbose_name_plural': 'Commodités'},
        ),
        migrations.AlterModelOptions(
            name='compagniemaritime',
            options={'verbose_name': 'Compagnie maritime', 'verbose_name_plural': 'Compagnies maritimes'},
        ),
        migrations.AlterModelOptions(
            name='pays',
            options={'ordering': ['nom'], 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'verbose_name': 'Port de déchargement (POD)', 'verbose_name_plural': 'Ports de déchargement (POD)'},
        ),
        migrations.AlterModelOptions(
            name='pol',
            options={'verbose_name': 'Port de chargement (POL)', 'verbose_name_plural': 'Ports de chargement (POL)'},
        ),
        migrations.AlterModelOptions(
            name='siteempotage',
            options={'verbose_name': "Site d'empotage", 'verbose_name_plural': "Sites d'empotage"},
        ),
        migrations.AlterModelOptions(
            name='siteselection',
            options={'verbose_name': 'Site de sélection', 'verbose_name_plural': 'Sites de sélection'},
        ),
    ]
