# Generated by Django 6.0.7 on 2026-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0002_alter_commodite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='drapeau',
            field=models.ImageField(blank=True, null=True, upload_to='pays/drapeaux/'),
        ),
    ]
