# Generated by Django 6.0.7 on 2026-07-16 16:27

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0003_pays_drapeau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodite',
            name='icon',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='commodites/icons/'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='drapeau',
            field=apps.common.fields.WebPImageField(blank=True, null=True, upload_to='pays/drapeaux/'),
        ),
    ]
